In [1]:
import numpy as np

t = np.array([
  [4, 8],
  [3, 5]
])

t

array([[4, 8],
       [3, 5]])

In [2]:
np.einsum('ij', t)

array([[4, 8],
       [3, 5]])

In [3]:
np.einsum('ji', t)

array([[4, 3],
       [8, 5]])

In [4]:
t.transpose()

array([[4, 3],
       [8, 5]])

In [5]:
np.einsum('ii', t)

9

In [6]:
np.einsum('jj', t)

9

In [7]:
np.einsum('ij->i', t)

array([12,  8])

In [8]:
np.einsum('ij->j', t)

array([ 7, 13])

In [9]:
np.einsum('ji->i', t)

array([ 7, 13])

In [10]:
np.einsum('ji->j', t)

array([12,  8])

In [11]:
np.einsum('ij->ji', t)

array([[4, 3],
       [8, 5]])

In [12]:
np.einsum('ji->ji', t)

array([[4, 8],
       [3, 5]])

In [13]:
np.einsum('ji->ij', t)

array([[4, 3],
       [8, 5]])